main: dev.by1337.fparticle.FParticlePlugin
name: FParticle
version: 1.2
author: By1337
api-version: "1.16"
website: 'https://github.com/By1337/FastParticle'
softdepend:
  - ViaVersion
commands:
  fparticle:
    aliases:
      - fp